name: API Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Output
        run: |
          echo "TOKEN: ${{ vars.TOKEN }}"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          TOKEN: ${{ vars.TOKEN }}
